// Field lists mirrored from client initialFormState/FIELD_CONFIG to ensure
// the backend can enrich responses so no fields are hidden or omitted.

export const FORM_FIELDS_BY_TYPE = {
  birth: [
    "registrationNumber",
    "mainRegistrationRecordNumberAm",
    "registrationDateEth",
    "registrationTimeHourAm",
    "registrationRegion",
    "registrationZone",
    "registrationWoreda",
    "registrationCity",
    "registrationSubCity",
    "registrationKebele",
    "region",
    "zone",
    "birthPlaceCity",
    "birthPlaceSubCity",
    "birthPlaceWoreda",
    "birthPlaceKebele",
    "woreda",
    "kebele",
    "childNameEn",
    "childNameAm",
    "childFullNameAm",
    "childFullNameEn",
    "fatherNameEn",
    "fatherNameAm",
    "grandfatherNameEn",
    "grandfatherNameAm",
    "childGrandfatherName",
    "sex",
    "age",
    "nationality",
    "birthDate",
    "birthTime",
    "birthPlaceType",
    "birthInfoNumberAm",
    "birthType",
    "birthHelpAm",
    "childWeightAm",
    "midwifeLevel",
    "placeOfBirthEn",
    "placeOfBirthAm",
    "childPhoto",
    "idCardImage",
    "uploadedform",
    "signedConsentPhoto",
    "registrationRegion",
    "registrationZone",
    "registrationWoreda",
    "registrationCity",
    "registrationSubCity",
    "registrationKebele",
    "motherFullNameAm",
    "motherFullNameEn",
    "motherSex",
    "motherBirthDate",
    "motherBirthPlace",
    "motherIdOrPassport",
    "motherEducationLevel",
    "motherOccupation",
    "motherReligionAm",
    "motherMaritalStatusAm",
    "motherNationality",
    "motherEthnicityAm",
    "motherEducationLevelAm",
    "motherOccupationAm",
    "fatherFullNameAm",
    "fatherFullNameEn",
    "fatherBirthPlace",
    "fatherSex",
    "fatherBirthDate",
    "fatherIdOrPassport",
    "fatherEducationLevel",
    "fatherOccupation",
    "fatherReligion",
    "fatherMaritalStatusAm",
    "fatherNationality",
    "fatherFatherName",
    "fatherGrandfatherName",
    "fatherEthnicity",
    "fatherEducationLevelAm",
    "fatherOccupationAm",
    "guardianFullName",
    "guardianOccupationEn",
    "guardianWorkAddressAm",
    "guardianHouseNoAm",
    "guardianMobileAm",
    "registrarNameAm",
    "registrarFatherNameAm",
    "registrarGrandNameAm",
    "registrarDateAm",
  ],
  marriage: [
    "registrationNumber",
    "mainRegistrationRecordNumberAm",
    "registrationDateEth",
    "registrationTimeHourAm",
    "registrationRegion",
    "registrationZone",
    "registrationWoreda",
    "registrationCity",
    "registrationSubCity",
    "registrationKebele",
    "husbandNameEn",
    "husbandNameAm",
    "husbandFatherEn",
    "husbandFatherAm",
    "husbandGrandfatherEn",
    "husbandGrandfatherAm",
    "husbandBirthDate",
    "husbandNationality",
    "husbandPhoto",
    "husbandReligionAm",
    "husbandPrevMaritalStatusAm",
    "wifeNameEn",
    "wifeNameAm",
    "wifeFatherEn",
    "wifeFatherAm",
    "wifeGrandfatherEn",
    "wifeGrandfatherAm",
    "wifeBirthDate",
    "wifeNationality",
    "wifePhoto",
    "wifeReligionAm",
    "wifePrevMaritalStatusAm",
    "marriageDate",
    "marriagePlaceEn",
    "marriagePlaceAm",
    "marriageRegion",
    "marriageZone",
    "marriageCity",
    "marriageSubCity",
    "marriageWoreda",
    "marriageKebele",
    "certificateDate",
    "consentForm",
  ],
  death: [
    "registrationNumber",
    "mainRegistrationRecordNumberAm",
    "registrationDateEth",
    "registrationTimeHourAm",
    "registrationRegion",
    "registrationZone",
    "registrationWoreda",
    "registrationCity",
    "registrationSubCity",
    "registrationKebele",
    "deathRegion",
    "deathZone",
    "deathCity",
    "deathSubCity",
    "deathWoreda",
    "deathKebeleAm",
    "deathKebele",
    "deceasedNameEn",
    "deceasedNameAm",
    "deceasedFatherEn",
    "deceasedFatherAm",
    "deceasedGrandfatherEn",
    "deceasedGrandfatherAm",
    "deceasedNationality",
    "deceasedIdNumberAm",
    "deceasedTitleAm",
    "deceasedSex",
    "deceasedAgeAm",
    "deceasedBirthDate",
    "deceasedResidence",
    "deceasedEthnicity",
    "deceasedReligion",
    "deceasedEducation",
    "deceasedJob",
    "deceasedMaritalStatusAm",
    "deceasedPhoto",
    "deathDate",
    "deathLocationType",
    "deathPlaceRegion",
    "deathPlaceZone",
    "deathPlaceSubCity",
    "deathPlaceWoreda",
    "deathPlaceKebele",
    "causeOfDeath",
    "deathProofTypeAm",
    "deathProofNumber",
    "burialPlace",
    "requesterName",
    "requesterFather",
    "requesterGrand",
    "requesterRegistrationDate",
    "requesterRelation",
    "requesterIdNumber",
    "deathSignedConsent",
    "registrarNameAm",
    "registrarFatherNameAm",
    "registrarGrandNameAm",
    "registrarDate",
  ],
  divorce: [
    // Registration details
    "registrationNumber",
    "mainRegistrationRecordNumberAm",
    "registrationDateEth",
    "registrationTimeHourAm",
    "registrationRegion",
    "registrationZone",
    "registrationWoreda",
    "registrationCity",
    "registrationSubCity",
    "registrationKebele",
    // Place of divorce
    "divorceRegion",
    "divorceZone",
    "divorceCity",
    "divorceSubCity",
    "divorceWoreda",
    "divorceKebele",
    "divorceKebeleAm",
    // Spouse 1
    "divorceSpouse1NameEn",
    "divorceSpouse1NameAm",
    "divorceSpouse1FatherNameEn",
    "divorceSpouse1FatherNameAm",
    "divorceSpouse1GrandfatherNameEn",
    "divorceSpouse1GrandfatherNameAm",
    "divorceSpouse1BirthPlaceEn",
    "divorceSpouse1BirthPlaceAm",
    "divorceSpouse1ResidenceEn",
    "divorceSpouse1ResidenceAm",
    "divorceSpouse1NationalityAm",
    "divorceSpouse1IdAm",
    "divorceSpouse1BirthDate",
    "divorceSpouse1Ethnicity",
    "divorceSpouse1ReligionAm",
    "divorceSpouse1EducationAm",
    "divorceSpouse1JobAm",
    "divorceSpouse1Photo",
    // Spouse 2
    "divorceSpouse2NameEn",
    "divorceSpouse2NameAm",
    "divorceSpouse2FatherNameEn",
    "divorceSpouse2FatherNameAm",
    "divorceSpouse2GrandfatherNameEn",
    "divorceSpouse2GrandfatherNameAm",
    "divorceSpouse2BirthPlaceEn",
    "divorceSpouse2BirthPlaceAm",
    "divorceSpouse2ResidenceEn",
    "divorceSpouse2ResidenceAm",
    "divorceSpouse2NationalityAm",
    "divorceSpouse2IdAm",
    "divorceSpouse2BirthDate",
    "divorceSpouse2Ethnicity",
    "divorceSpouse2ReligionAm",
    "divorceSpouse2EducationAm",
    "divorceSpouse2JobAm",
    "divorceSpouse2Photo",
    // Divorce information
    "divorceMarriageDate",
    "divorceMarriagePlace",
    "divorceReasonAm",
    "divorceDate",
    "divorceCourtNameAm",
    "divorceCourtRegNoAm",
    "divorceChildrenCountAm",
    "divorceConsentProofAm",
    // Registrar Information
    "registrarName",
    "registrarFatherNameAm",
    "registrarGrandNameAm",
    "registrarDate",
  ],
  special: [
    "specialType",
    "specialDescription",
    "specialDocuments",
  ],
};

export function enrichDataWithAllFields(event) {
  try {
    const data = (event && event.data) || {};
    const type = event?.type;
    const fields = FORM_FIELDS_BY_TYPE[type] || [];
    const out = { ...data };
    for (const k of fields) {
      if (out[k] === undefined) out[k] = null;
    }
    return out;
  } catch {
    return (event && event.data) || {};
  }
}


